### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ghost** [denysdovhan/inboxer#29]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at EventEmitter.ipcMain.on (/Applications/Inboxer.app/Contents/Resources/app.asar/app/main/index.js:155:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Applications/Inboxer.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

**Comment by denysdovhan** [comment]
Thanks for reporting! Should be fixed by #44. Thanks, @JohnnyBui!

Please, update to the version `v1.1.0` :pray:
