### ISSUE TITLE
Exception on new mail shortcut

### ISSUE THREAD

**Issue by wedi** [denysdovhan/inboxer#56]
Pressing <kbd>Ctrl</kbd>+<kbd>N</kbd> to write a new mail causes the following error if the main window is minimized.

```javascript
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at sendKeybinding (/Applications/Inboxer.app/Contents/Resources/app.asar/app/main/utils.js:16:6)
    at click (/Applications/Inboxer.app/Contents/Resources/app.asar/app/main/menu.js:80:7)
    at MenuItem.click (/Applications/Inboxer.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Inboxer.app/Contents/Resources/electron.asar/browser/api/menu.js:34:15)
```

---
Inboxer 1.1.2
Electron 1.8.4
darwin x64 16.7.0

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
